import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import { ThemeProvider } from "../../components/darkTheme";
import "./globals.css";
import { LanguageProvider} from '../../components/LanguageProvider'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BistroPulse",
  description: "Generated by create next app",
   icons: {
    icon: "/favicon.ico", // Ensure this path is correct
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
         <Toaster position="top-right" reverseOrder={false} />
        <LanguageProvider>{children}</LanguageProvider>
       </ThemeProvider>
      </body>
    </html>
  );
}
